# Generated by Django 3.0.8 on 2020-07-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_idx',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
