# Generated by Django 3.0.8 on 2020-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_idx', models.CharField(max_length=50)),
                ('bus_id', models.CharField(max_length=50)),
            ],
        ),
    ]
