# Generated by Django 3.0.8 on 2020-07-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bus_bus_idx'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
