version: '3'

services:
  nginx:
    build: ./nginx
    #image: nginx:latest
    ports:
      - 1337:80
    volumes:
      - ./:/app
      - ./nginx:/etc/nginx.conf.d
    depends_on:
      - web
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tajo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=321
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=tajo
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=321
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: gunicorn tajo_backend.wsgi:application --bind 0.0.0.0:8000
#python manage.py runserver 0.0.0.0:8000
#         ./start.sh

    volumes:
      - ./:/app/
    expose:
      - "8000"
