version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tajo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=321
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  tajo_test_v2:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=tajo
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=321
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: 
         ./start.sh
    volumes:
      - ./:/app/
