# Generated by Django 3.0.8 on 2020-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=30)),
                ('ars_id', models.CharField(max_length=30)),
                ('st_name', models.CharField(max_length=50)),
                ('pos_x', models.DecimalField(decimal_places=15, max_digits=20)),
                ('pos_y', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_nm', models.CharField(max_length=20)),
                ('route_id', models.CharField(max_length=20)),
            ],
        ),
    ]
