# Generated by Django 3.0.8 on 2020-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_idx', models.CharField(max_length=50)),
                ('bus_id', models.CharField(max_length=50)),
                ('route_nm', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_idx', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
