# Generated by Django 3.0.8 on 2020-07-20 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_bus_bus_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
