# Generated by Django 3.0.8 on 2020-07-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bus_bus_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_idx',
        ),
    ]
