# Generated by Django 3.0.8 on 2020-07-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBuzzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
            ],
        ),
    ]
