# Generated by Django 3.0.8 on 2020-07-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBuzzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=150)),
                ('stn_id', models.CharField(max_length=150)),
                ('route_nm', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Buzzer',
            },
        ),
    ]
