# Generated by Django 3.0.8 on 2020-07-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbuzzer',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='callbuzzer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='callbuzzer',
            name='bus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Bus'),
        ),
        migrations.AddField(
            model_name='callbuzzer',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='callbuzzer',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
