# Generated by Django 3.0.8 on 2020-07-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callbuzzer',
            old_name='bus',
            new_name='bus_id',
        ),
        migrations.RenameField(
            model_name='callbuzzer',
            old_name='user',
            new_name='user_id',
        ),
    ]
