# Generated by Django 3.0.8 on 2020-07-18 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0002_auto_20200713_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbuzzer',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
