# Generated by Django 3.0.8 on 2020-07-22 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0002_auto_20200722_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbuzzer',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='callbuzzer',
            name='user',
        ),
        migrations.AddField(
            model_name='callbuzzer',
            name='bus_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callbuzzer',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
