# Generated by Django 3.0.8 on 2020-07-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0003_auto_20200722_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callbuzzer',
            unique_together={('stn_id', 'bus_id')},
        ),
    ]
